default_context:
  project_name: 'rader-app'
  project_slug: 'rader-app'
  domain_main: 'rader-app.com'
  domain_staging: 'stage.rader-app.com'
  docker_swarm_stack_name_main: 'rader-app-com'
  docker_swarm_stack_name_staging: 'stage-rader-app-com'
  secret_key: '2eb8205737448b0362a381e1a01c80b065e46ffebdb91a5de60743e6a28798ea'
  first_superuser: 'admin@rader-app.com'
  first_superuser_password: 'john8895'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.rader-app.com", "https://stage.rader-app.com", "https://rader-app.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@rader-app.com'
  postgres_password: '8e61b39c338a245c0c8ad291b2f5d92127860e5864add44455aa328122072f5b'
  pgadmin_default_user: 'admin@rader-app.com'
  pgadmin_default_user_password: 'john8895'
  traefik_constraint_tag: 'rader-app.com'
  traefik_constraint_tag_staging: 'stage.rader-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:john8895'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
